### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by dtrifonoff** [lorenzo/pinky#28]
After update to version 1.0.8 stopped wort cyrillic support, On version 1.0.7 work fine.

[Example](https://prnt.sc/DIF6OMHdXNYk)

**Comment by lorenzo** [comment]
would you be able to make a fix?

**Comment by dtrifonoff** [comment]
This work perfect ( old source)

1.  _$document->loadHTML(mb\_convert\_encoding($html, 'HTML-ENTITIES', 'UTF-8'));_

For new upgraded source code, this work perfect:

    2. $document->loadHTML(_htmlspecialchars\_decode_(_htmlentities_(_sprintf_(**'%s%s'**, **'\<?xml encoding="utf-8" ?>'**, $html), _**HTML\_ENTITIES**_, **"UTF-8"**)));

Short call:   
 _3. $document->loadHTML(htmlspecialchars\_decode(htmlentities(sprintf(**'%s%s'**, **'\<?xml encoding="utf-8" ?>'**, $html))));_   
It's may not always work correctly for all charsets.

I'm not sure which option is better.

**Comment by Lustmored** [comment]
We have same problem, but with UTF in general. All special (polish in this case) characters got messed up with 1.0.8, like this:

![image](https://user-images.githubusercontent.com/2358046/211537309-ee32acf7-c265-4504-b012-571de7ca9d2d.png)

Downgrading to 1.0.7 fixes this

**Comment by stof** [comment]
A reproducing case requires providing the input string. Otherwise, there is no way to reproduce it.

**Comment by broiniac** [comment]
The sentence from @Lustmored would be `Twoje zamówienie oczekuje na wpłatę zadatku`.

**Comment by genby8** [comment]
`Pinky\transformString('Привет мир!')->saveHTML()`
"lorenzo/pinky": "1.0.7" print: `"<html><body><p>Привет мир!</p></body></html>"`
"lorenzo/pinky": "1.0.8" print: `"<html><body><p>ÐŸÑ€Ð¸Ð²ÐµÑ‚ Ð¼Ð¸Ñ€!</p></body></html>"`
PHP 8.0.15

**Comment by stof** [comment]
I'm working on a fix

**Comment by dtrifonoff** [comment]
Тhis is a fix 

$document->loadHTML(_htmlspecialchars\_decode_(_htmlentities_(_sprintf_(**'%s%s'**, **'\<?xml encoding="utf-8" ?>'**, $html), _**HTML\_ENTITIES**_, **"UTF-8"**)));

**Comment by stof** [comment]
The fix used in https://github.com/tijsverkoyen/CssToInlineStyles/blob/c42125b83a4fa63b187fdf29f9c93cb7733da30c/src/CssToInlineStyles.php#L116 is to use `mb_encode_numericentity($html, [0x80, 0x10FFFF, 0, 0x1FFFFF], 'UTF-8')` to encode entities.

However, contrary to the comment of @genby8, both this replacement and the `mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8')` usage in Pinky 1.0.7 return cyrillic characters as entities, not as Unicode chars (at least on PHP 8.1, I haven't tried on 8.0.15) when using `->saveHTML` without argument.
See https://github.com/tijsverkoyen/CssToInlineStyles/blob/c42125b83a4fa63b187fdf29f9c93cb7733da30c/src/CssToInlineStyles.php#L128 for the trick to return Unicode characters directly.

**Comment by broiniac** [comment]
@dtrifonoff I'm not sure it won't break anything. For string `Dziękujemy!`
1.0.7 version result would be `Dzi&#281;kujemy!`
Your proposal would return `<?xml encoding="utf-8" ?>Dziękujemy!`

Meanwhile I found this:
https://www.php.net/manual/en/function.mb-convert-encoding.php#127529
This solution will return `Dzi&#281;kujemy!`

**Comment by genby8** [comment]
> The fix used in https://github.com/tijsverkoyen/CssToInlineStyles/blob/c42125b83a4fa63b187fdf29f9c93cb7733da30c/src/CssToInlineStyles.php#L116 is to use `mb_encode_numericentity($html, [0x80, 0x10FFFF, 0, 0x1FFFFF], 'UTF-8')` to encode entities.
> 
> However, contrary to the comment of @genby8, both this replacement and the `mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8')` usage in Pinky 1.0.7 return cyrillic characters as entities, not as Unicode chars (at least on PHP 8.1, I haven't tried on 8.0.15) when using `->saveHTML` without argument. See https://github.com/tijsverkoyen/CssToInlineStyles/blob/c42125b83a4fa63b187fdf29f9c93cb7733da30c/src/CssToInlineStyles.php#L128 for the trick to return Unicode characters directly.

This raw:

"lorenzo/pinky": "1.0.7" print: 
`<html><body><p>&#1055;&#1088;&#1080;&#1074;&#1077;&#1090; &#1084;&#1080;&#1088;!</p></body></html>`

"lorenzo/pinky": "1.0.8" print: 
`<html><body><p>&ETH;&#159;&Ntilde;&#128;&ETH;&cedil;&ETH;&sup2;&ETH;&micro;&Ntilde;&#130; &ETH;&frac14;&ETH;&cedil;&Ntilde;&#128;!</p></body></html>`
