### ISSUE TITLE
Can we lower the PHP version requirements to 5.3.2 ?

### ISSUE THREAD

**Issue by tchapi** [lorenzo/pinky#5]
Hi

I notice you require **PHP >= 5.6.0**. Is there a strong reason to do so ?
We're looking at using your library for https://github.com/gremo/ZurbInkBundle/pull/3 and keeping the low requirements would be a good thing for us.

I have not seen anything in https://secure.php.net/manual/en/migration54.incompatible.php (_and the subsequent changes_) that would break your library, but I may be missing something.

Thanks a lot

**Comment by gremo** [comment]
I think the only reason is the `yield `keyword, introduced with PHP 5.5.

**Comment by lorenzo** [comment]
hmm, I rather not as that is more work for me. You can fork this library and remove the functions using newer php features
