### ISSUE TITLE
composer.json should state it requires ext-xsl 

### ISSUE THREAD

**Issue by allan-simon** [lorenzo/pinky#9]
otherwise you get the notice: 
```
Notice: Use of undefined constant XSL_SECPREF_READ_FILE - assumed 'XSL_SECPREF_READ_FILE'  
```

which took me a while to figure out why it was not working :)

**Comment by dsmink** [comment]
@allan-simon Yes, it took me a while to figure this out to, but indeed the composer.json file shoud require the ext-xsl extension for it to work.

**Comment by lorenzo** [comment]
Added to composer.json
